id: PE41B73B3
initial_creation_type: ocr
source_metadata:
  volumes:
    02d659fcf6924807b401c64f42abe6ac:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
